### ISSUE TITLE
无法下载 

### ISSUE THREAD

**Issue by al123xiaaaa** [tyrone2015/91porn#2]
root@default:~/scripts# ls
91.sh
root@default:~/scripts# chmod +x 91.sh 
root@default:~/scripts# ls
91.sh
root@default:~/scripts# ./91.sh 
plase input your link!
http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17944    0 17944    0     0  68881      0 --:--:-- --:--:-- --:--:-- 81563
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    762      0 --:--:-- --:--:-- --:--:--   879
./91.sh: line 27: urlencode: command not found
--2015-12-18 00:27:58--  http://homemade/
正在解析主机 homemade... 失败：未知的名称或服务。
wget: 无法解析主机地址 “homemade”
--2015-12-18 00:27:58--  http://video./
正在解析主机 video.... 失败：没有与主机名关联的地址。
wget: 无法解析主机地址 “video.”
root@default:~/scripts# ls
91  91.sh  list_temp  少妇自慰给我看-Chinese
root@default:~/scripts# ./91.sh 
plase input your link!
http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16008    0 16008    0     0  64215      0 --:--:-- --:--:-- --:--:-- 76228
vid is null
root@default:~/scripts# ./91.sh 
plase input your link!
http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16008    0 16008    0     0  69352      0 --:--:-- --:--:-- --:--:-- 79247
vid is null

**Comment by tyrone2015** [comment]
你需要安装扩展包，刚刚我试了下，是可以的，还有，这个网站是需要翻墙的

**Comment by tyrone2015** [comment]
~/test/91porn $ sh -x 91.sh
+ echo plase input your link!
plase input your link!
+ read url
http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
+ cookie=-b language=cn_CN;watch_times=0
+ browser=-A Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
+ proxy=-x 180.73.0.10:81
+ [ -d ./91 ]
+ rm -f -R ./91
+ mkdir ./91
+ echo+  http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
grep v.php
+ echo http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
+ download
+ read line var
+ [ ! -n http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb ]
+ [ http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb !=  ]
+ [ ! -f ./91/list_temp ]
+ touch ./91/list_temp
+ cat ./91/list_temp
+ grep http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
+ curl http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb -b language=cn_CN;watch_times=0 -A Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 -o ./91/video_page
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17944    0 17944    0     0  21144      0 --:--:-- --:--:-- --:--:-- 28756
+ cat ./91/video_page
+ grep -o ^so.*file.*'
+ cut -d ' -f 4
+ vid=140783
+ echo http://www.91porn.com/view_video.php?viewkey=f1992fdefe2bd30d7beb
+ checkvid 140783
+ [ ! -n 140783 ]
+ cat ./91/video_page
+ + cut -d ' -f 4
grep -o ^so.*seccode.*'
+ seccode=0d9bfb298c1007c1e7848b5f256e40f2
+ cat ./91/video_page
+ grep -o ^so.*max_vid.*'
+ cut -d ' -f 4
+ max_vid=140681
+ cat ./91/video_page
+ sed -n -e H;${x;s!.*<head[^>]*>\(.*\)</head>.*!\1!;tnext;b;:next;s!.*<title>\(.*\)</title>.*!\1!p}
+ tr -d \n
+ sed s/^[[:space:]]\+//
+ title=少妇自慰给我看-Chinese homemade video
+ jsonurl=http://91porn.com/getfile.php?VID=140783&seccode=0d9bfb298c1007c1e7848b5f256e40f2&max_vid=140681&mp4=1
+ curl http://91porn.com/getfile.php?VID=140783&seccode=0d9bfb298c1007c1e7848b5f256e40f2&max_vid=140681&mp4=1 -b language=cn_CN;watch_times=0 -A Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 -o ./91/down_Json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    307      0 --:--:-- --:--:-- --:--:--   400
+ readDown_Json
+ + read line var
cut -d & -f 1
+ [ ! -n file=http%3A%2F%2Fa.91zp.co%3A8080%2Fmp4hd%2F140783.mp4%3Fst%3DjgWbh0Z25bOADtoGk5t37A%26e%3D1450425190&domainUrl=http://91porn.ro.lt&imgUrl=http://img.file.am/91porn/> ]
+ [ file=http%3A%2F%2Fa.91zp.co%3A8080%2Fmp4hd%2F140783.mp4%3Fst%3DjgWbh0Z25bOADtoGk5t37A%26e%3D1450425190&domainUrl=http://91porn.ro.lt&imgUrl=http://img.file.am/91porn/> !=  ]
+ cat ./91/down_Json
+ urlencode -d file=http%3A%2F%2Fa.91zp.co%3A8080%2Fmp4hd%2F140783.mp4%3Fst%3DjgWbh0Z25bOADtoGk5t37A%26e%3D1450425190&domainUrl=http://91porn.ro.lt&imgUrl=http://img.file.am/91porn/>
+ cat ./91/down_Json
+ cut -d = -f 2-4
+ cut -d & -f 1-2
+ videolink=http://a.91zp.co:8080/mp4hd/140783.mp4?st=jgWbh0Z25bOADtoGk5t37A&e=1450425190
+ echo http://a.91zp.co:8080/mp4hd/140783.mp4?st=jgWbh0Z25bOADtoGk5t37A&e=1450425190
+ awk -F . {print $NF}
+ cut -d ? -f 1
+ fileType=mp4
+ name=少妇自慰给我看-Chinese homemade video.mp4
+ wget -c -O 少妇自慰给我看-Chinese homemade video.mp4 http://a.91zp.co:8080/mp4hd/140783.mp4?st=jgWbh0Z25bOADtoGk5t37A&e=1450425190
--2015-12-18 05:51:50--  http://homemade/
Resolving homemade (homemade)... failed: Name or service not known.
wget: unable to resolve host address `homemade'
--2015-12-18 05:51:50--  http://video.mp4/
Resolving video.mp4 (video.mp4)... failed: Name or service not known.
wget: unable to resolve host address `video.mp4'
--2015-12-18 05:51:50--  http://a.91zp.co:8080/mp4hd/140783.mp4?st=jgWbh0Z25bOADtoGk5t37A&e=1450425190
Resolving a.91zp.co (a.91zp.co)... 192.240.109.123
Connecting to a.91zp.co (a.91zp.co)|192.240.109.123|:8080... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 24038629 (23M), 20434408 (19M) remaining [video/mp4]
Saving to: `\345\260\221\345\246\207\350\207\252\346\205\260\347\273\231\346\210\221\347\234\213-Chinese'

18% [++++++++++++++++++++===>                                                                                                              ] 4,358,909   16.1K/s   in 96s
