### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by serm12** [tyrone2015/91porn#3]
sh 91.sh -u "http://91porn.com/view_video.php?viewkey=986baf66fc0703aafeea"
======your must setting -u option=========
http://91porn.com
* About to connect() to proxy 112.124.51.136 port 1080 (#0)
*   Trying 112.124.51.136... Connection refused
* couldn't connect to host
* Closing connection #0

curl: (7) couldn't connect to host
cat: ./91/video_page: No such file or directory

cat: ./91/video_page: No such file or directory

cat: ./91/video_page: No such file or directory
video vid is null,plase use proxy or change proxy

**Comment by tyrone2015** [comment]
已经解决
