### ISSUE TITLE
请问这是什么意思？

### ISSUE THREAD

**Issue by tea1111980** [tyrone2015/91porn#4]
-p 是指http代理ip和端口，为了解决浏览次数限制 ？

我们都知道91有访客 访问视频数量的限制，但是这个设置代理 对于访问限制有什么帮助呢？

难道你的意思是指的，当访客的观看次数用完的时候，换一个代理地址，就相当于观看次数初始化了？

**Comment by tyrone2015** [comment]
你可以这样理解  目前我测试到的是有效的，如果失效了请告诉我
